version: "3.8"

services:
  postgres:
    container_name: nest-project-pg
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-project
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: nest-project-cache
    image: redis
    ports:
      - 6380:6380
    volumes:
      - ./data/redis:/data
